substitutions:
  name: leafsense-amg8833
  friendly_name: LeafSense AMG8833

packages:
  leafsense:
    url: https://github.com/FishKepping/LeafSense
    ref: main
    files:
      - leafsense-amg8833.yaml
    refresh: 1h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret leafsense_api_key
  custom_services: true
